# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl }:
{
  manix = {
    pname = "manix";
    version = "d08e7ca185445b929f097f8bfb1243a8ef3e10e4";
    src = fetchgit {
      url = "https://github.com/mlvzk/manix";
      rev = "d08e7ca185445b929f097f8bfb1243a8ef3e10e4";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "1b7xi8c2drbwzfz70czddc4j33s7g1alirv12dwl91hbqxifx8qs";
    };
  };
  zk = {
    pname = "zk";
    version = "977625bb3d6728efdd7ea8d2376aed238af85972";
    src = fetchgit {
      url = "https://github.com/mickael-menu/zk";
      rev = "977625bb3d6728efdd7ea8d2376aed238af85972";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "1hpffdiy8x9zkq17ssdbjp8a744jfqpgck8f0r1dxnb44885lcmf";
    };
  };
}
